### ISSUE TITLE
<nz-* snippet not working

### ISSUE THREAD

**Issue by Svetomechc** [ng-alain/ng-zorro-vscode#11]
Where is **nz-button**?

![image](https://user-images.githubusercontent.com/36156020/59602700-0facd500-9110-11e9-8992-7ee85b1baec3.png)

![image](https://user-images.githubusercontent.com/36156020/59602721-22bfa500-9110-11e9-929a-197199aaf6e9.png)

**Comment by cipchk** [comment]
@Svetomechc You can check error information via open `help` - `Toggle Developer tools`.

> I think may be no automatic installation of dependency packages when vscode installs ng-zorro-vscode extensions, #8

**Comment by Svetomechc** [comment]
I checked there, no errors.

**Comment by Svetomechc** [comment]
What is the suggested workaround?

**Comment by cipchk** [comment]
I think you have tried to uninstall and then reinstalled. ~_~

**Comment by Svetomechc** [comment]
@cipchk already tried ofc

**Comment by cipchk** [comment]
@Svetomechc I have a way you can try it.

1. Go to `/Users/<Your Name>/.vscode/extensions/cipchk.ng-zorro-vscode-7.3.4/` path
2. Clean `node_modules`
3. Running `yarn`
4. restart vscode

**Comment by Svetomechc** [comment]
@cipchk there isn't a `node_modules` folder there:

![image](https://user-images.githubusercontent.com/36156020/59609079-65d54480-911f-11e9-8bba-94ff2eac2b5b.png)

**Comment by cipchk** [comment]
@Svetomechc ingore step 2.

**Comment by Svetomechc** [comment]
@cipchk that worked, thanks!

**Comment by Svetomechc** [comment]
@cipchk although not for a very long time... and now repeating these steps does nothing at all.

**Comment by Donmen** [comment]
@cipchk 我也碰到这个问题，试了你上面的方法，还是解决不了。调试没有报错，但传入的值是空的。。

**Comment by cipchk** [comment]
@Donmen 抱歉，我想不到有什么办法可以解决了；目前我在 mac 下并无发生过这类情况，而 windows 下好像会有这种很奇怪的情况，总感觉应该是权限问题吧，导致无法自动执行安装依赖。

**Comment by ChaoQunPeng** [comment]
我在ng-zorro-vscode-8.3.0下的snippets.json似乎没有发现有nzs-button触发前缀。。。

**Comment by cipchk** [comment]
fixed by `11` version.
