### ISSUE TITLE
插件在项目中不显示

### ISSUE THREAD

**Issue by styick** [ng-alain/ng-zorro-vscode#12]
插件在开发项目中没有工作，但是新建一个单独的html倒是可以正常工作， 这大概和什么有关系？

**Comment by cipchk** [comment]
项目中会去查找是否包含 `ng-zorro-antd` 类库，若没有则认为非 NG-ZORRO 项目，从而不开启。

**Comment by styick** [comment]
这么说很奇怪，我只是在桌面新建一个html打开就能用，根本没有 ng-zorro-antd 类库，而我的项目里到处都是用的库里的模板却不工作
<img width="827" alt="屏幕快照 2019-08-01 下午4 21 26" src="https://user-images.githubusercontent.com/17807333/62277312-798efd00-b478-11e9-9c94-d713dcd5f810.png">
<img width="779" alt="屏幕快照 2019-08-01 下午4 20 17" src="https://user-images.githubusercontent.com/17807333/62277317-7d228400-b478-11e9-8c10-8dbf7b70f882.png">

**Comment by cipchk** [comment]
是的，这一规则只对项目有效，反之非项目不会做任何检查；我认为这是合理的，是否在某个项目中是使用 ng-zorro 再来决定是否使用本插件，否则会导致在一个项目中智能提醒列表中包含许多 ng-zorro 相关的，但实际非 zorro 项目这些东西是无意义的。

**Comment by styick** [comment]
找到原因了。我的项目头目录package.json是没有这个库的，但是子目录有子项目有单独的package.json，这种情况下插件不显示。这种情况会考虑修改吗？

**Comment by cipchk** [comment]
@styick 可以自行在子目录内增加 `ng-zorro-antd` 依赖。
