### ISSUE TITLE
vscode 提示 'nz-tabset' is not a known element: 

### ISSUE THREAD

**Issue by Bigredorange** [ng-alain/ng-zorro-vscode#13]
'nz-tabset' is not a known element:
1. If 'nz-tabset' is an Angular component, then verify that it is part of this module.
2. If 'nz-tabset' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
NG-ZORRO Snippets 9.01
widows  vscode version 1.44

how to fix this problem? thank you !

**Comment by cipchk** [comment]
@Bigredorange You muse import `ng-zorro-antd/tabs`, pls refer to:

- https://ng.ant.design/docs/getting-started/en#import-component-module
- https://ng.ant.design/components/tabs/en

**Comment by Bigredorange** [comment]
thanks, my brother.
