### ISSUE TITLE
在Angular 9.1.1版本下会失效，无法正确识别

### ISSUE THREAD

**Issue by lightman0215** [ng-alain/ng-zorro-vscode#16]
这是在Angular 9.1.1下的截图
![](https://files.catbox.moe/o53lnj.png)

这是在Angular 8.2.0下的截图
![](https://files.catbox.moe/by742t.png)

在Angular 7下也是正常，不知道为何9.1.1的版本会这样

**Comment by cipchk** [comment]
这是 vscode 插件，除了会检测 package.json 内是否有包含 ng-zorro-antd 的依赖包体外，没有其他开关会影响了。

**Comment by lightman0215** [comment]
> 这是 vscode 插件，除了会检测 package.json 内是否有包含 ng-zorro-antd 的依赖包体外，没有其他开关会影响了。

那应该就是Angular Language Service这个插件导致的了

**Comment by lightman0215** [comment]
最终发现的确是Angular Language Service的问题，如果项目不是在根目录，嵌套了一层文件夹，Angular Language Service也失效了
