### ISSUE TITLE
Can I disable hints in the .ts file?

### ISSUE THREAD

**Issue by kinglionsoft** [ng-alain/ng-zorro-vscode#4]
Nice works！
Is there any way to disable hints in the .ts file?
I want NzTreeNode, but ....
![image](https://user-images.githubusercontent.com/20222245/40033053-4d989ff0-5829-11e8-9743-bd41d43e83e4.png)

**Comment by cipchk** [comment]
In the light of `template:`, but actually it is unneccessary.

**Comment by kinglionsoft** [comment]
Instant response ! I'm wondering how did you do that.
