### ISSUE TITLE
这个东西不全，好多都出不来

### ISSUE THREAD

**Issue by gamergamer8888** [ng-alain/ng-zorro-vscode#5]
在做today-ng的例子，用这个插件，结果好多都出不来
比如 右边list菜单，[nzMode="inline" ] inline出不来，[nzInlineCollapsed] 也出不来
还有好多好多，快点补全吧！

**Comment by cipchk** [comment]
请问 `nzInlineCollapsed`、`nzMode` 是属于哪个组件？能否提供明确的信息。

**Comment by gamergamer8888** [comment]
> 请问 `nzInlineCollapsed`、`nzMode` 是属于哪个组件？能否提供明确的信息。

nz-menu组件，例子参考
https://github.com/NG-ZORRO/today-ng-steps/blob/master/tutorial/2.md 
List组件 这一段
```
<ul nz-menu
    [nzTheme]="'dark'"
    [nzMode]="'inline'"
    [nzInlineCollapsed]="isCollapsed">
  <li nz-menu-item
      [nzSelected]="currentListUuid === 'today'"
      (click)="click('today')">
```
[nzSelected] 这个也出不来，其他还有很多

**Comment by cipchk** [comment]
所谓其他还有很多，是指？

**Comment by gamergamer8888** [comment]
> 所谓其他还有很多，是指？

我不可能全部记住，在做这个练习的过程中，很多出不来，列的几个是有印象的，就这样

**Comment by gamergamer8888** [comment]
这就关了？也是醉了

**Comment by cipchk** [comment]
所有组件模板都是以一个完整示例呈现，所以基本上在模板中已经存在的属性，没有做为单属性形式模板。

另，我会增强那些高频率组件的单属性模板。但这并不属性本 issues，我会在另一个 pr 中完成。
