### ISSUE TITLE
Intellisense of 'ng-zorro snippets' VSCode extension is showing Chinese characters instead of english characters

### ISSUE THREAD

**Issue by phani428** [ng-alain/ng-zorro-vscode#6]
It will be great if intellisense shows English characters instead of Chinese characters for others who don't know Chinese language

ex:  nz-form

**Comment by cipchk** [comment]
In fact limited by https://github.com/Microsoft/vscode/issues/56777, it‘s currently in `中文 (English)` format.

![tim 20181208113735](https://user-images.githubusercontent.com/2987467/49681495-ace1dd80-fadd-11e8-98fe-9bc6a7218502.png)

I think as more and more English users, the default English version will be more friendly.

**Comment by phani428** [comment]
Thanks @cipchk
