### ISSUE TITLE
vs安装之后，只显示nzs-radio-button，但是没有nz-button?

### ISSUE THREAD

**Issue by robinloop** [ng-alain/ng-zorro-vscode#8]
RT

**Comment by cipchk** [comment]
打开 Help -> Toggle Developer Tools 查看是否有什么错误。

**Comment by robinloop** [comment]
按照步骤新建ng项目，add ng-alian脚手架后，打开一个html页，报错信息是

激活扩展“cipchk.ng-alain-vscode”失败: Cannot find module 'less'

跟这个有关系吗？

上午时候node-sass那个安装失败了，下载和python版本问题，刚刚我把这些重弄了，但是依然报上面的错误

追加:
我把alain的snippet删掉，重新安装了zorro的snippet，控制台没报错，但是依然只有nzs，没有nz

**Comment by cipchk** [comment]
@robinloop zorro-vscode 不依赖额外npm包，但所有触发必须是 `<` 开头；其实判断 zorro-vscode 是否有效，可以找一个 `.html` 后缀并鼠标移到任你本个 nz-zorro-antd 组件是否显示文档。

另，alain-vsocde 依赖了 less，这个问题第一次遇到，但我不觉得是哪里引起的，可能最接近一个相关的ISSUES是 [#14411](https://github.com/Microsoft/vscode/issues/14411)；尝试进入 extentions 的目录如果是 windows 应该是 `C:\Users(用户)\Administrator(你的用户名).vscode\extensions\ng-alain-vscode` 进入目录后手动安装依赖包，即：`yarn`

**Comment by robinloop** [comment]
我都删除了重新安装的，只安装了zorro-vscode，snippet提示还是只有nzs
鼠标hover设置为true了，但是并没有显示文档
页面是可以正常显示的
看起来像你说的zorro-vscode没有生效，有可能是什么原因呢？

**Comment by SilverHowe** [comment]
作者@cipchk 的源码中就已经没有nz-button了，现在都是prefix: 'nzs'了。基础的用法都不再支持了吗？

**Comment by cipchk** [comment]
@robinloop 参考 https://github.com/ng-alain/ng-zorro-vscode/issues/11#issuecomment-502687639 试一下，关闭此 issues。
